import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :rom_to_the_com, RomToTheComWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: "PHX_LOG_LEVEL" |> System.get_env("info") |> String.to_atom()

config :rom_to_the_com, enable_sentry: true

config :sentry,
  enable_source_code_context: true,
  root_source_code_paths: [File.cwd!()]

config :opentelemetry, traces_exporter: :none

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
